In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from itertools import product
from collections import defaultdict

In [4]:
from sklearn.metrics import roc_auc_score

In [5]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)

In [6]:
series = pd.read_csv('train.csv',index_col=['sequence','subject','step'])
series.head()

                       sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  \
sequence subject step
0        47      0     -0.196291   0.112395        1.0   0.329204  -1.004660
                 1     -0.447450   0.134454        1.0  -0.658407   0.162495
                 2      0.326893  -0.694328        1.0   0.330088   0.473678
                 3      0.523184   0.751050        1.0   0.976991  -0.563287
                 4      0.272025   1.074580        1.0  -0.136283   0.398579

                       sensor_05  sensor_06  sensor_07  sensor_08  sensor_09  \
sequence subject step
0        47      0     -0.131638  -0.127505   0.368702       -0.1  -0.963873
                 1      0.340314  -0.209472  -0.867176        0.2  -0.301301
                 2      1.280479  -0.094718   0.535878        1.4   1.002168
                 3     -0.720269   0.793260   0.951145       -0.3  -0.995665
                 4      0.044877   0.560109  -0.541985       -0.9   1.055636

                       sensor_10  sensor_11  sensor_12
sequence subject step
0        47      0     -0.985069   0.531893   4.751492
                 1      0.082733  -0.231481   0.454390
                 2      0.449221  -0.586420  -4.736147
                 3     -0.434290   1.344650   0.429241
                 4      0.812631   0.123457  -0.223359

In [7]:
labels = pd.read_csv('train_labels.csv', index_col=['sequence'])
labels.head()

          state
sequence
0             0
1             1
2             1
3             1
4             1

In [12]:
test = pd.read_csv('test.csv',index_col=['sequence','subject','step'])

In [13]:
test.head()

                       sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  \
sequence subject step
25968    684     0      2.427357  19.639706        1.0  -1.466372  -1.289973
                 1     -4.950541 -21.747899        1.0   0.983186  -0.569053
                 2      1.136012 -10.756303        1.0   1.016814   0.964157
                 3      0.806028   6.504202        1.0  -0.179646   0.969221
                 4      1.288253   5.552521        1.0  -0.493805  -1.036124

                       sensor_05  sensor_06  sensor_07  sensor_08  sensor_09  \
sequence subject step
25968    684     0     -4.207928   2.486339  -2.493893        8.0  -1.123555
                 1      1.845924  -3.887978   1.727481       -2.9   0.395231
                 2      2.454749   0.312386   1.154198       -5.6   1.114162
                 3     -1.035153  -0.457195   0.254962       -2.7  -0.588873
                 4     -1.126402   2.008197  -0.730534        0.0   0.899566

                       sensor_10  sensor_11  sensor_12
sequence subject step
25968    684     0     -1.673048  10.980453   0.419011
                 1     -0.882233  -1.871399  -0.008525
                 2      1.525273 -11.584362   0.139812
                 3      0.608761  -4.241770  -0.462916
                 4     -1.259615  -0.472222  -0.121483

In [9]:
series.index.get_level_values(1).unique()

Int64Index([ 47,  66, 542, 437, 510, 246, 520,  78, 526,   4,
            ...
            506,  45,  39, 181, 490, 616, 486, 202,  73, 112],
           dtype='int64', name='subject', length=672)

In [14]:
test.index.get_level_values(1).unique()

Int64Index([684, 935, 924, 769, 764, 988, 790, 965, 887, 921,
            ...
            958, 943, 786, 839, 975, 720, 802, 832, 738, 714],
           dtype='int64', name='subject', length=319)

In [32]:
tmp = sorted(series.index.get_level_values(1).unique().to_list())

In [33]:
tmp

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671]

In [35]:
for subject in sorted(test.index.get_level_values(1).unique().to_list()):
    print(subject)

672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990

The objects are different between the dataset.

In [39]:
data_all = pd.concat([series, test])
data_all.shape

(2291160, 13)

In [43]:
mean = data_all.mean(axis=0)
mean

sensor_00    0.000363
sensor_01   -0.001039
sensor_02   -0.217954
sensor_03   -0.002250
sensor_04   -0.001293
sensor_05   -0.001735
sensor_06   -0.000827
sensor_07    0.000242
sensor_08   -0.000019
sensor_09    0.001277
sensor_10   -0.000139
sensor_11   -0.003435
sensor_12   -0.008596
dtype: float64

In [46]:
std = data_all.std(axis=0)
std

sensor_00     2.747429
sensor_01     4.466203
sensor_02     2.310527
sensor_03     4.261084
sensor_04     1.749201
sensor_05     1.601893
sensor_06     3.370294
sensor_07     3.099620
sensor_08     4.663098
sensor_09     2.659309
sensor_10     1.980841
sensor_11     4.490679
sensor_12    39.669326
dtype: float64

In [45]:
series

                       sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  \
sequence subject step
0        47      0     -0.196291   0.112395   1.000000   0.329204  -1.004660
                 1     -0.447450   0.134454   1.000000  -0.658407   0.162495
                 2      0.326893  -0.694328   1.000000   0.330088   0.473678
                 3      0.523184   0.751050   1.000000   0.976991  -0.563287
                 4      0.272025   1.074580   1.000000  -0.136283   0.398579
...                          ...        ...        ...        ...        ...
25967    327     55    -0.282844  -1.217437  -1.666153   0.586726  -0.930698
                 56     0.130603   0.349790  -1.666153  -0.324779   0.775324
                 57    -0.579598   0.429622  -1.666153   0.319469   0.308861
                 58     1.278980   1.711134  -1.522820   0.802655  -0.460541
                 59    -1.136012  -3.702731  -1.332820  -0.766372  -0.430027

                       sensor_05  sensor_06  sensor_07  sensor_08  sensor_09  \
sequence subject step
0        47      0     -0.131638  -0.127505   0.368702       -0.1  -0.963873
                 1      0.340314  -0.209472  -0.867176        0.2  -0.301301
                 2      1.280479  -0.094718   0.535878        1.4   1.002168
                 3     -0.720269   0.793260   0.951145       -0.3  -0.995665
                 4      0.044877   0.560109  -0.541985       -0.9   1.055636
...                          ...        ...        ...        ...        ...
25967    327     55    -0.451010  -0.651184   0.368702        0.4   0.008671
                 56    -0.332835   0.099271   0.122137       -0.2   0.644509
                 57     0.282723  -0.512750   0.012214       -1.6  -0.424133
                 58    -0.055348   2.405282   0.043511        1.9   0.283960
                 59    -0.091997  -2.512750  -0.022901       -1.1  -0.653902

                       sensor_10  sensor_11  sensor_12
sequence subject step
0        47      0     -0.985069   0.531893   4.751492
                 1      0.082733  -0.231481   0.454390
                 2      0.449221  -0.586420  -4.736147
                 3     -0.434290   1.344650   0.429241
                 4      0.812631   0.123457  -0.223359
...                          ...        ...        ...
25967    327     55    -0.723536  -0.353909  -0.914749
                 56     0.691407  -0.613169  -0.515772
                 57     0.716855   1.628601   0.928389
                 58    -0.914914   0.364198   0.211424
                 59    -0.418516  -1.453704  -1.561381

[1558080 rows x 13 columns]

In [47]:
series / std

                       sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  \
sequence subject step
0        47      0     -0.071445   0.025166   0.432802   0.077258  -0.574354
                 1     -0.162861   0.030105   0.432802  -0.154516   0.092897
                 2      0.118982  -0.155463   0.432802   0.077466   0.270797
                 3      0.190427   0.168163   0.432802   0.229282  -0.322025
                 4      0.099011   0.240603   0.432802  -0.031983   0.227863
...                          ...        ...        ...        ...        ...
25967    327     55    -0.102949  -0.272589  -0.721114   0.137694  -0.532070
                 56     0.047536   0.078319  -0.721114  -0.076220   0.443245
                 57    -0.210960   0.096194  -0.721114   0.074974   0.176573
                 58     0.465519   0.383130  -0.659079   0.188369  -0.263287
                 59    -0.413482  -0.829056  -0.576847  -0.179854  -0.245842

                       sensor_05  sensor_06  sensor_07  sensor_08  sensor_09  \
sequence subject step
0        47      0     -0.082177  -0.037832   0.118951  -0.021445  -0.362452
                 1      0.212445  -0.062152  -0.279768   0.042890  -0.113300
                 2      0.799354  -0.028104   0.172885   0.300230   0.376853
                 3     -0.449636   0.235368   0.306859  -0.064335  -0.374407
                 4      0.028015   0.166190  -0.174855  -0.193005   0.396959
...                          ...        ...        ...        ...        ...
25967    327     55    -0.281548  -0.193213   0.118951   0.085780   0.003260
                 56    -0.207776   0.029455   0.039404  -0.042890   0.242359
                 57     0.176493  -0.152138   0.003940  -0.343120  -0.159490
                 58    -0.034551   0.713671   0.014038   0.407454   0.106779
                 59    -0.057430  -0.745558  -0.007388  -0.235895  -0.245892

                       sensor_10  sensor_11  sensor_12
sequence subject step
0        47      0     -0.497298   0.118444   0.119777
                 1      0.041767  -0.051547   0.011454
                 2      0.226783  -0.130586  -0.119391
                 3     -0.219245   0.299431   0.010820
                 4      0.410245   0.027492  -0.005631
...                          ...        ...        ...
25967    327     55    -0.365267  -0.078810  -0.023059
                 56     0.349047  -0.136543  -0.013002
                 57     0.361894   0.362662   0.023403
                 58    -0.461882   0.081101   0.005330
                 59    -0.211282  -0.323716  -0.039360

[1558080 rows x 13 columns]

In [49]:
series = (series - mean) / std
series.head()

                       sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  \
sequence subject step
0        47      0     -0.026185   0.005919   0.322475   0.018783  -0.327190
                 1     -0.059458   0.007025   0.322475  -0.035610   0.054270
                 2      0.043126  -0.034524   0.322475   0.018832   0.155974
                 3      0.069130   0.037937   0.322475   0.054460  -0.182937
                 4      0.035857   0.054156   0.322475  -0.006854   0.131429

                       sensor_05  sensor_06  sensor_07  sensor_08  sensor_09  \
sequence subject step
0        47      0     -0.049540  -0.010907   0.038273  -0.004594  -0.136957
                 1      0.134381  -0.018123  -0.090362   0.009203  -0.043266
                 2      0.500765  -0.008020   0.055673   0.064389   0.141050
                 3     -0.278931   0.070154   0.098896  -0.013792  -0.141452
                 4      0.019248   0.049628  -0.056515  -0.041385   0.148610

                       sensor_10  sensor_11  sensor_12
sequence subject step
0        47      0     -0.250948   0.027311   0.003242
                 1      0.021191  -0.010543   0.000511
                 2      0.114594  -0.028144  -0.002787
                 3     -0.110577   0.067614   0.000495
                 4      0.207213   0.007057   0.000080

### do a brute force xgboost

In [53]:
seqs = series.index.get_level_values(0).unique()

In [51]:
X = np.zeros((len(seqs),60*13),dtype=np.float16)

In [52]:
for idx, seq in enumerate(seqs):
    if (idx % 100 == 0):  print(idx)
    X[idx] = series.loc[seq].values.reshape(1,-1)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900

In [55]:
X.shape

(25968, 780)

In [56]:
y = np.zeros(len(X), dtype = np.int0)

In [57]:
for idx,seq in enumerate(seqs):
    y[idx] = labels.loc[seq].values[0]

In [ ]:
def gridsearch_xgboost(params, X, y, obj="binary:logistic"):
    ''' the params include both the fit and the booster params '''
    
    param_names, param_vals = zip(*list(params.items()))
    id_booster, id_fit = [], []
    for idx, name in enumerate(param_names):
        if (name=='early_stopping_rounds'):
            id_fit.append(idx)
        else:
            id_booster.append(idx)
    
    best_test_score = 999.0
    for val_combination in product(*param_vals):
        param_fit, param_booster = {}, {}
        param_fit['eval_metric'] = 'auc'
        for idx in id_fit:
            param_fit[param_names[idx]] = val_combination[idx]
        for idx in id_booster:
            param_booster[param_names[idx]] = val_combination[idx]
        print(f"param_fit: {param_fit}")
        print(f"param_booster: {param_booster}")
        
        clf = XGBClassifier(**param_booster, objective=obj, use_label_encoder=False)
        result = defaultdict(list)
        for train_idx, test_idx in kf.split(X):
            X_train, y_train = X[train_idx], y[train_idx]
            X_test, y_test = X[test_idx], y[test_idx]
            param_fit['eval_set'] = [(X_test, y_test)]            
            clf.fit(X_train, y_train, **param_fit, verbose=True)
            if hasattr(clf, 'best_ntree_limit'):
                result['ntree'].append(clf.best_ntree_limit)
            else:
                result['ntree'].append(clf.n_estimators)            
            result['score'].append(roc_auc_score(y_test, clf.predict_proba(X_test)[:,1]))
            print(f'stop at {result["ntree"][-1]}, score={result["score"][-1]}')

        mean_test_score = np.mean(result['score'])
        print(f"mean_test_score={mean_test_score}")
        if mean_test_score > best_test_score:
            best_test_score = mean_test_score
            best_param_booster = param_booster
            best_param_booster['n_estimators'] = np.int32(np.mean(result['ntree']))
    
    return best_param_booster

In [ ]:
params = {'gamma': [0],
          'max_depth': [6],
          'min_child_weight': [0.0],
          'n_estimators': [10000],
          'early_stopping_rounds': [50],
          'learning_rate': [0.3]}

In [ ]:
best_param_booster = gridsearch_xgboost(params, X, y)